from challenge import ChallengeCommand
from form import FormCommand
from granny import GrannyCommand
from head_to_head import HeadToHeadCommand
from help import HelpCommand
from leaderboard import LeaderboardCommand
from odds import OddsCommand
from profile import ProfileCommand
from record import RecordCommand
from stats import StatsCommand
from spree import SpreeCommand
