api_token: <SLACK API TOKEN>

bot_id: <BOT SLACK ID>

server_host: <SERVER HOST ADDRESS>

server_token: <SERVER HOST REST FRAMEWORK TOKEN>

slack_channel_id: <SLACK CHANNEL ID>

log_filename: poolbot.log
log_level: 10 # debug

# PLUGIN / COMMANDS

record_emojis:
  - beers
  - partyparrot
  - sunglasses
  - ambulance
  - champagne
  - muscle
  - boom

# slack IDs of all NFC bots
nfc_bots:
  - <BOT SLACK ID>
  - <BOT SLACK ID>